# Generated by Django 5.0.6 on 2024-07-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('screen_size', models.CharField(max_length=10)),
                ('price_euros', models.FloatField()),
            ],
        ),
    ]
